name: bennu_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  riverpod: ^1.0.3
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.12.2
  firebase_core:
  firebase_auth:
  firebase_storage:
  firebase_messaging:
  firebase_analytics:
  firebase_crashlytics:
  flutter_local_notifications:
  sqflite:
  passkeys: ^1.0.2
  flutter_secure_storage:
  flutter_stripe: 
  qr_flutter: ^4.1.0
  http: ^1.1.4
  flutter_riverpod: ^1.0.3+1
  url_launcher:
  fake_cloud_firestore: ^2.4.1+1
  video_player: ^2.7.1
  visibility_detector: ^0.4.0+2
  solana: ^0.30.0
  image_picker: ^1.0.4
  hooks_riverpod:
  share_plus: ^7.2.1
  material_design_icons_flutter: ^5.0.6595

dependency_overrides:
  http: ^0.13.3

dev_dependencies:
  mockito: ^5.0.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2 # ここにバージョン番号を指定する

flutter:
  uses-material-design: true
  assets:
    - assets/resized_1.png  # 画像ファイルのパスを指定する
  # flutter_iconsの設定をflutterセクションの中に入れる
flutter_icons:
  android: true
  ios: true
  image_path: assets/resized_1.png

