name: bennu
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  riverpod: ^1.0.3
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.12.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  firebase_storage: ^11.5.5
  firebase_messaging: ^14.7.8
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  flutter_local_notifications: 
  sqflite:
  passkeys: ^1.3.2
  flutter_stripe: ^9.0.0
  qr_flutter: ^4.1.0
  http: ^1.1.4
  flutter_riverpod: 
  url_launcher:
  fake_cloud_firestore: ^2.4.1+1
  video_player: ^2.7.1
  visibility_detector: ^0.4.0+2
  solana: ^0.30.0
  image_picker: ^1.0.4
  hooks_riverpod:
  share_plus: ^7.2.1
  material_design_icons_flutter: ^5.0.6595
  tapioca: ^1.0.6+1
  camera: ^0.10.5+5
  intl: ^0.18.1
  shared_preferences: ^2.0.8
  path_provider:
  flutter_secure_storage: ^9.0.0

dependency_overrides:
  http: ^0.13.3

dev_dependencies:
  mockito: ^5.0.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/resized_1.png
    - assets/berryIcon_transparent.png
    - assets/kkrn_icon_user_5.png
    - assets/dummy_qr.png
    
flutter_icons:
  android: true
  ios: true
  image_path: assets/resized_1.png

